name: ReadAloudApp
options:
  bundleIdPrefix: com.readAloud
  deploymentTarget:
    iOS: 17.0
targets:
  ReadAloudApp:
    type: application
    platform: iOS
    sources:
      # Only include compilable source code here
      - path: Sources/ReadAloudApp
    resources:
      # This is the correct, dedicated place for your resource folder.
      # It ensures everything inside is copied to the app bundle.
      - path: rsc
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.readAloud.ReadAloudApp
      PRODUCT_NAME: $(TARGET_NAME)
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_OBJC_BRIDGING_HEADER: Sources/ReadAloudApp/ReadAloudApp-Bridging-Header.h
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: "Sources/ReadAloudApp/rsc"
    dependencies: []
  ReadAloudAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/ReadAloudAppTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.readAloud.ReadAloudAppTests
    dependencies:
      - target: ReadAloudApp 