name: ReadAloudApp
options:
  bundleIdPrefix: com.readAloud
  deploymentTarget:
    iOS: 17.0
targets:
  ReadAloudApp:
    type: application
    platform: iOS
    sources:
      - Sources/ReadAloudApp
    settings:
      INFOPLIST_FILE: Sources/ReadAloudApp/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.readAloud.ReadAloudApp
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_OBJC_BRIDGING_HEADER: Sources/ReadAloudApp/ReadAloudApp-Bridging-Header.h
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: "Sources/ReadAloudApp/Resources"
    dependencies: []
  ReadAloudAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/ReadAloudAppTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.readAloud.ReadAloudAppTests
    dependencies:
      - target: ReadAloudApp 